[pytest]
addopts = --cov=. --cov-report=html --cov-fail-under=90 -v
testpaths = tests
filterwarnings = 
    ignore::DeprecationWarning
    ignore::UserWarning
junit_family = xunit2
python_files = test_*.py
python_classes = Test*
python_functions = test_*
msg_format = %(levelname)s %(message)s
