"""
cumulative_parser.py
Parses DY Patil attendance report PDFs and Excel files.
Drop this file next to app.py.
"""

import re
import io
from typing import Optional

# ── PDF parsing ──────────────────────────────────────────────────────────────

def _safe_int(val):
    try:
        s = str(val).strip()
        return int(float(s)) if s else 0
    except Exception:
        return 0

def _safe_float(val):
    try:
        return round(float(str(val).strip()), 2)
    except Exception:
        return 0.0

def _detect_meta(text: str) -> dict:
    meta = {"year": "", "semester": "", "program": "", "department": "", "division": ""}
    m = re.search(r"Academic Year ([\d\-]+),\s*Semester\s*-\s*(\w+)", text, re.IGNORECASE)
    if m:
        meta["year"] = m.group(1).strip()
        meta["semester"] = m.group(2).strip()
    m = re.search(r"Program:\s*(.+)", text)
    if m:
        prog = m.group(1).strip()
        meta["program"] = prog
        div_m = re.search(r"Div\.?\s*([A-Z])", prog)
        meta["division"] = div_m.group(1) if div_m else ""
        prog_up = prog.upper()
        if "AIML" in prog_up:
            meta["department"] = "AIML"
        elif "AIDS" in prog_up:
            meta["department"] = "AIDS"
        elif "IT" in prog_up and "COMP" not in prog_up:
            meta["department"] = "IT"
        else:
            meta["department"] = "CS"
    return meta


def parse_pdf(filepath: str) -> dict:
    """
    Parse a DY Patil attendance PDF.
    Returns:
      {
        meta: {year, semester, program, department, division},
        subjects: [{name, code, conducted}],
        students: [{roll, name, total, pct, attended:[int,...]}]
      }
    """
    try:
        import pdfplumber
    except ImportError:
        raise RuntimeError("pdfplumber not installed. Run: pip install pdfplumber")

    result = {"meta": {}, "subjects": [], "students": []}

    with pdfplumber.open(filepath) as pdf:
        first_text = pdf.pages[0].extract_text() or ""
        result["meta"] = _detect_meta(first_text)

        # Collect all table rows across all pages
        all_rows = []
        for page in pdf.pages:
            tables = page.extract_tables()
            if tables:
                all_rows.extend(tables[0])

        subj_names = []
        subj_codes = []
        conducted = []
        student_rows = []

        for row in all_rows:
            if not row or len(row) < 4:
                continue
            c0, c1, c2 = str(row[0] or ""), str(row[1] or ""), str(row[2] or "")

            if "TOTAL NO." in c2.upper() or "CONDUCTED" in c2.upper() or "TOTAL LECTURES" in c2.upper():
                # conducted counts in cols 3..-2
                conducted = row[3:-2]

            elif c0.strip() in ("", "None") and c2.strip() in ("", "None") and row[3] and "U24" in str(row[3]):
                # Subject codes row
                subj_codes = row[3:-2]

            elif "SR" in c0.upper() and "NO" in c0.upper():
                # Header row — subject names
                subj_names = row[3:-2]

            elif c0.strip().lstrip("0").isdigit() and c1.strip():
                # Student data row
                student_rows.append(row)

        result["subjects"] = []
        for i, name in enumerate(subj_names):
            result["subjects"].append({
                "name": (name or "").replace("\n", " ").strip(),
                "code": (subj_codes[i] if i < len(subj_codes) else "").replace("\n", "").strip(),
                "conducted": _safe_int(conducted[i]) if i < len(conducted) else 0,
            })

        for row in student_rows:
            if not row[1]:
                continue
            attended_raw = row[3:-2]
            result["students"].append({
                "roll": str(row[1]).strip(),
                "name": str(row[2] or "").strip(),
                "total": _safe_int(row[-2]),
                "pct": _safe_float(row[-1]),
                "attended": [_safe_int(x) for x in attended_raw],
            })

    return result


# ── Excel parsing ─────────────────────────────────────────────────────────────

# ── Excel parsing ─────────────────────────────────────────────────────────────

def parse_excel(filepath_or_bytes, filename: str = "") -> list:
    """
    Parse an Excel attendance sheet (must follow the DY Patil layout or
    the downloadable template generated by this system).
    Parses all sheets in the workbook and returns a list of dictionaries.
    """
    try:
        from openpyxl import load_workbook
    except ImportError:
        raise RuntimeError("openpyxl not installed.")

    import io
    if isinstance(filepath_or_bytes, (bytes, bytearray)):
        wb = load_workbook(io.BytesIO(filepath_or_bytes), data_only=True)
    else:
        wb = load_workbook(filepath_or_bytes, data_only=True)

    results = []

    for sheet_name in wb.sheetnames:
        ws = wb[sheet_name]
        rows = list(ws.iter_rows(values_only=True))
        if not rows or len(rows) < 5:
            continue

        # Find header row (contains "ROLL" or "SR")
        header_idx = None
        for i, row in enumerate(rows):
            if any("ROLL" in str(c or "").upper() for c in row):
                header_idx = i
                break

        if header_idx is None:
            continue

        result = {"meta": {}, "subjects": [], "students": []}

        # Try to read metadata from first few rows
        meta_text = ""
        for row in rows[:header_idx]:
            meta_text += " ".join(str(c or "") for c in row) + "\n"
        
        result["meta"] = _detect_meta(meta_text)

        # Fallback metadata from sheet name if missing
        sheet_up = sheet_name.upper()
        if not result["meta"].get("department"):
            if "AIML" in sheet_up:
                result["meta"]["department"] = "AIML"
            elif "AIDS" in sheet_up or "AI&DS" in sheet_up:
                result["meta"]["department"] = "AIDS"
            elif "IT" in sheet_up:
                result["meta"]["department"] = "IT"
            elif "COMP" in sheet_up or "CS" in sheet_up:
                result["meta"]["department"] = "CS"
            else:
                result["meta"]["department"] = "CS" # general fallback

        if not result["meta"].get("division"):
            import re
            div_m = re.search(r"DIV\.?\s*([A-D])", sheet_up)
            if div_m:
                result["meta"]["division"] = div_m.group(1)
            elif "DIV A" in sheet_up or "DIV. A" in sheet_up or "DIV-A" in sheet_up or "DIV_A" in sheet_up:
                result["meta"]["division"] = "A"
            elif "DIV B" in sheet_up or "DIV. B" in sheet_up or "DIV-B" in sheet_up or "DIV_B" in sheet_up:
                result["meta"]["division"] = "B"
            elif "DIV C" in sheet_up or "DIV. C" in sheet_up or "DIV-C" in sheet_up or "DIV_C" in sheet_up:
                result["meta"]["division"] = "C"
            elif "DIV D" in sheet_up or "DIV. D" in sheet_up or "DIV-D" in sheet_up or "DIV_D" in sheet_up:
                result["meta"]["division"] = "D"
            else:
                result["meta"]["division"] = "A" # general fallback

        if not result["meta"].get("semester"):
            import re
            sem_m = re.search(r"SEMESTER\s*-\s*(\w+)", meta_text, re.IGNORECASE)
            if sem_m:
                result["meta"]["semester"] = sem_m.group(1).strip()
            elif "SEM-I" in sheet_up or "SEM I " in sheet_up or "SEM_I" in sheet_up:
                result["meta"]["semester"] = "I"
            elif "SEM-II" in sheet_up or "SEM II" in sheet_up or "SEM_II" in sheet_up:
                result["meta"]["semester"] = "II"
            elif "SEM-III" in sheet_up or "SEM III" in sheet_up or "SEM_III" in sheet_up:
                result["meta"]["semester"] = "III"
            elif "SEM-IV" in sheet_up or "SEM IV" in sheet_up or "SEM_IV" in sheet_up:
                result["meta"]["semester"] = "IV"
            elif "SEM-V" in sheet_up or "SEM V" in sheet_up or "SEM_V" in sheet_up:
                result["meta"]["semester"] = "V"
            elif "SEM-VI" in sheet_up or "SEM VI" in sheet_up or "SEM_VI" in sheet_up:
                result["meta"]["semester"] = "VI"
            elif "SEM-VII" in sheet_up or "SEM VII" in sheet_up or "SEM_VII" in sheet_up:
                result["meta"]["semester"] = "VII"
            elif "SEM-VIII" in sheet_up or "SEM VIII" in sheet_up or "SEM_VIII" in sheet_up:
                result["meta"]["semester"] = "VIII"
            else:
                result["meta"]["semester"] = "II"

        if not result["meta"].get("year"):
            import re
            year_m = re.search(r"Academic Year ([\d\-]+)", meta_text, re.IGNORECASE)
            if year_m:
                result["meta"]["year"] = year_m.group(1).strip()
            else:
                result["meta"]["year"] = "2025-26"

        header = rows[header_idx]
        name_col = next((i for i, h in enumerate(header) if "NAME" in str(h or "").upper()), 2)
        total_col = next((i for i, h in enumerate(header) if str(h or "").strip().upper() == "TOTAL"), len(header) - 2)
        subj_cols = list(range(name_col + 1, total_col))

        # Build subjects from header
        for ci in subj_cols:
            result["subjects"].append({
                "name": str(header[ci] or "").strip(),
                "code": "",
                "conducted": 0,
            })

        # Search for conducted counts row below header (up to 10 rows below)
        conducted_row_idx = None
        roll_col = next((i for i, h in enumerate(header) if "ROLL" in str(h or "").upper()), 1)
        
        for r_idx in range(header_idx + 1, min(header_idx + 10, len(rows))):
            row = rows[r_idx]
            name_cell = str(row[name_col] or "").strip().upper() if name_col < len(row) else ""
            roll_cell = str(row[roll_col] or "").strip().upper() if roll_col < len(row) else ""
            row_str = " ".join(str(c or "").upper() for c in row)
            
            is_conducted_row = (
                any(x in name_cell or x in roll_cell for x in ("TOTAL", "CONDUCTED", "LECTURES")) or
                "TOTAL NO" in row_str or "TOTAL LECTURES" in row_str or "LECTURES CONDUCTED" in row_str
            )
            if is_conducted_row:
                for j, ci in enumerate(subj_cols):
                    if j < len(result["subjects"]):
                        result["subjects"][j]["conducted"] = _safe_int(row[ci])
                conducted_row_idx = r_idx
                break

        # Parse student rows
        pct_col  = next((i for i, h in enumerate(header) if "%" in str(h or "")), len(header) - 1)

        for row_idx in range(header_idx + 1, len(rows)):
            row = rows[row_idx]
            if not row or roll_col >= len(row) or row[roll_col] is None:
                continue
            roll = str(row[roll_col]).strip()
            name = str(row[name_col] or "").strip() if name_col < len(row) else ""
            if not roll or roll.upper() in ("ROLL NO.", "ROLL"):
                continue
            # Skip conducted/header rows by content
            name_cell = str(row[name_col] or "").strip().upper() if name_col < len(row) else ""
            roll_cell = str(row[roll_col] or "").strip().upper()
            row_str = " ".join(str(c or "").upper() for c in row)
            
            is_metadata_row = (
                any(x in name_cell or x in roll_cell for x in ("TOTAL", "CONDUCTED", "LECTURES", "ACADEMIC YEAR")) or
                "TOTAL NO" in row_str or "TOTAL LECTURES" in row_str or "LECTURES CONDUCTED" in row_str or "ACADEMIC YEAR" in row_str
            )
            if is_metadata_row:
                continue
            if roll.lower() in ("none", "null"):
                continue
            
            attended = [_safe_int(row[ci]) if ci < len(row) else 0 for ci in subj_cols]
            total = _safe_int(row[total_col]) if total_col < len(row) else sum(attended)
            pct = _safe_float(row[pct_col]) if pct_col < len(row) else 0.0
            result["students"].append({
                "roll": roll,
                "name": name,
                "total": total,
                "pct": pct,
                "attended": attended,
            })
        results.append(result)

    return results


# ── Generic entry point ───────────────────────────────────────────────────────

def parse_attendance_file(filepath_or_bytes, filename: str):
    """Auto-detect format and parse."""
    fname = filename.lower()
    if fname.endswith(".pdf"):
        if isinstance(filepath_or_bytes, (bytes, bytearray)):
            import tempfile, os
            with tempfile.NamedTemporaryFile(delete=False, suffix=".pdf") as tmp:
                tmp.write(filepath_or_bytes)
                tmp_path = tmp.name
            try:
                return parse_pdf(tmp_path)
            finally:
                os.unlink(tmp_path)
        return parse_pdf(filepath_or_bytes)
    elif fname.endswith((".xlsx", ".xls")):
        return parse_excel(filepath_or_bytes, filename)
    else:
        raise ValueError(f"Unsupported file type: {filename}. Use .pdf or .xlsx")
