import secrets
import os

def generate_env():
    env_content = f"""# DY Patil ERP Environment Configuration
# Generated by init_secrets.py

# SECURITY
SECRET_KEY={secrets.token_hex(32)}
DEFAULT_STUDENT_PASSWORD={secrets.token_urlsafe(12)}
DEFAULT_FACULTY_PASSWORD={secrets.token_urlsafe(12)}
ADMIN_PASSWORD={secrets.token_urlsafe(16)}

# DATABASE
DATABASE_URL=postgresql://postgres:password@localhost:5432/antigravity_db
DB_POOL_MAX=100

# REDIS & CELERY
REDIS_URL=redis://localhost:6379/0
CELERY_BROKER_URL=redis://localhost:6379/1
CELERY_RESULT_BACKEND=redis://localhost:6379/1

# STORAGE
UPLOAD_PATH=uploads
"""
    
    if os.path.exists(".env"):
        confirm = input(".env already exists. Overwrite? (y/N): ")
        if confirm.lower() != 'y':
            print("Aborted.")
            return

    with open(".env", "w") as f:
        f.write(env_content)
    
    print("Generated .env with secure random secrets.")
    print("IMPORTANT: Update DATABASE_URL and REDIS_URL in .env to match your setup.")

if __name__ == "__main__":
    generate_env()
